### PR TITLE
add two code examples

### PR DESCRIPTION
**Pull request by ellennickles**
Two examples for Week 9: one sending text and another one sending an image from a webcam feed

In experimenting with a couple of RunwayML models, input and output specifications can vary from model to model even if the media type is the same--something for students to be aware of.

Also, I was not successful in sending an uploaded image file to Runway. I'm wondering if it could be related to what is mentioned at the end of this [thread](https://github.com/runwayml/processing-library/issues/5).

### CODE REVIEW

**Comment by ellennickles** [comment]
Figured it out:

Example 3, sending uploaded image file to a model in RunwayML:
[Send uploaded image file to RunwayML: Generate a caption with im2txt](https://editor.p5js.org/ima_ml/sketches/uGOBrA-Sl)

 (added in commit below)

**Comment by shiffman** [comment]
Amazing, this is exactly what I was working on, I like your examples better! Looks like maybe you are still making minor changes, let me know when I should merge!

**Comment by ellennickles** [comment]
We’re good to go!

**Comment by shiffman** [comment]
🎉

**Pull request merged**
