### PR TITLE
Week 6 Material: image data and CNNs

### PR DESCRIPTION
**Pull request by shiffman**
This is a start of the material for next week. My goals are the following:

* Discussion around collecting image datasets and working with MNIST and Google's Quick, Draw dataset.
* Training a image based model with `ml5.neuralNetwork()` and why it doesn't work well.
* What is a CNN and how does it improve upon a "vanilla" neural network.
* Demo a TensorFlow.js example training a model with a CNN.
* How to use `DoodleNet` in ml5.

Any thoughts, suggestions, feedback welcome!

This could also be a good time to revisit and discuss ethics around collecting data as it relates to faces and other kinds of content. Suggestions on readings and/or relevant artistic projects (like ImageNet Rouletter, Humans of AI, etc.) appreciated!

### CODE REVIEW

**Comment by shiffman** [comment]
Training an image model with `ml5.neuralNetwork()` (no CNN layer)! Works pretty well!

Screen Shot 2019-10-05 at 6 12 56 PM

**Comment by shiffman** [comment]
a cat drawing classified correctly

**Comment by shiffman** [comment]
Showing the doodles working.

**Comment by ellennickles** [comment]
I learned about the work of [Dr. Lisa Feldman Barrett](https://lisafeldmanbarrett.com) at the AI Now 2019 Symposium. Her research indicates that there is no scientific basis for detecting emotions according to facial expressions.

A major paper published this summer: [Emotional Expressions Reconsidered: Challenges to Inferring Emotion From Human Facial Movements](https://journals.sagepub.com/stoken/default+domain/10.1177%2F1529100619832930-FREE/pdf)

An article with an interview in The Verge about the paper above: [AI ‘EMOTION RECOGNITION’ CAN’T BE TRUSTED The belief that facial expressions reliably correspond to emotions is unfounded, says a new review of the field](https://www.theverge.com/2019/7/25/8929793/emotion-recognition-analysis-ai-machine-learning-facial-expression-review)

Here’s a talk from 2018: [Dr. Lisa Feldman Barrett: "Can Machines Perceive Emotion?" | Talks at Google](https://www.youtube.com/watch?v=HlJQXfL_GeM)

Might be necessary to share in conversation with Angelica Perez’s Recognizing Human Facial Expressions With Machine Learning, listed as a related project this week.

**Comment by joeyklee** [comment]
@ellennickles - Whoa thanks for sharing these! 

I'd be curious if, given this research, if we should also consider removing support for the face-api `expression` detection  feature. At the least, we should add in a `console.log()` that highlights this research so that anyone using the library with these expressions sees during development that this feature should be used with caution. It would be great to hear your thoughts on this @shiffman @AshleyJaneLewis @ellennickles

**Comment by shiffman** [comment]
Lots more to do here but merging as class starts in 30 minutes!

**Comment by shiffman** [comment]
Thank you for these @ellennickles! The theme for this week is when training your own image-based model with your own data rather than a pre-trained model or transfer learning. Drawings are a great dataset for this discussion since they are so different than what is in ImageNet. Facial expressions are similar in that respect but open up many complex privacy and ethical concerns.

@joeyklee I would advocate for removing the emotions from ml5. I have not seen them used effectively in a interactive media project (they tend to not be accurate and are more misleading than anything else) and this is an opportunity for students to train a model on their own facial expressions and consider these questions.

**Comment by joeyklee** [comment]
@shiffman Thanks for that feedback. I agree that the emotions are rarely used in an effective way. They also seem only to reflect hyper exaggerated expressions and quite likely western definitions/associations of "expressions". 

I do think that being able to showcase these issues can be instructive, but I'd opt for leaving them out of ml5 in favor of highlighting them through other apis.

**Comment by shiffman** [comment]
@joeyklee Agreed. I also think it's good for us to set precedent around intentional choices around  ml5 functionality.

**Pull request merged**
