### PR TITLE
adding Week3/SessionB pcomp example #3

### PR DESCRIPTION
**Pull request by ellennickles**
Adding a third example for Wednesday and a couple of additional resources

### CODE REVIEW

**Comment by ellennickles** [comment]
TODO:

- Add Pcomp labs for tone and servos to syllabus
- Borrow Arduino Unos / breadboards from Rob
- Grab LEDs and resistors from shop
- Check with Tom for extra breadboard wires
- Document camera & USB cables from ER
- Update slides

**Review by shiffman — APPROVED** [review]
This looks great @ellennickles! Shall I merge now or let me know when you would like me to merge?

**Comment by shiffman** [comment]
Also @ellennickles for the PoseNet examples, they should use the `ml5` way of access the parts directly by name! This is much simpler than the array indices. Here is an example you can use as a model.

https://editor.p5js.org/ml5/sketches/I-alLCVhX3S

```javascript
if (poses.length > 0) {
  let pose = poses[0].pose;
  ellipse(pose.nose.x, pose.nose.y, 20, 20);
}
```

(I'm happy to revise them, but don't have the arduino setup so not able to easily test to make sure I didn't break it.)

**Comment by ellennickles** [comment]
> for the PoseNet examples, they should use the `ml5` way of access the parts directly by name!

Oh yes, thank you! I didn't know you could do that until you mentioned it in class on Monday. I'll update Example 2 and test it today. Example 3 is already using names.

**Pull request merged**
