### PR TITLE
Creating a Rubric for Evaluation of Assignments

### PR DESCRIPTION
**Pull request by shiffman**
This is really barebones at present, but serves as a starting point. Should be fleshed out quite a bit more. #7

### CODE REVIEW

**Review by lydiajessup — COMMENTED** [review]
I like the example shared by @joeyklee in particular with the scales for each component (understanding, application, etc) - in addition to this being helpful for all of us to make consistent assessments, I think sharing a rubric like this with the students for their blogposts and assignments ahead of time would be useful for them as well to know what to aim for.

**Comment by ellennickles** [comment]
Another reference, this fall's [creative computing syllabus from Mimi O](https://itp.nyu.edu/classes/cc-f19/syllabus/)

**Comment by shiffman** [comment]
Thanks @lydiajessup, I agree, that example was great! There were aspects of it that aren't one-to-one matches with this course, but maybe I can work to simplify it a bit and create a similar chart.

@ellennickles This is awesome, I really love the "How to do well in this course" section! 

These are great resources. I'm not sure if I'll have a more complete version of this by tomorrow, butr I'll set Wednesday as a goal.

**Comment by shiffman** [comment]
@joeyklee, @AshleyJaneLewis, @ellennickles I've rewritten this based on the discussion on Friday. I'm going to merge this, but please add comments in an issue (or here) and feel free to create your own pull request with suggested edits / additions / etc.

**Pull request merged**
