### PR TITLE
Material for Week 8 (RNN Training) and Week 9 (RunwayML)

### PR DESCRIPTION
**Pull request by shiffman**

### CODE REVIEW

**Comment by shiffman** [comment]
@ellennickles I'm going to merge this, it's just a skeleton of Week 9 so far and you should feel free to open your own branch and add any and all links to Runway resources and materials!

**Comment by ellennickles** [comment]
> @ellennickles I'm going to merge this, it's just a skeleton of Week 9 so far and you should feel free to open your own branch and add any and all links to Runway resources and materials!

Ok! Is your thought to still keep all discussion and examples about GANs for week 10? If so, then I'll start with non-GAN resources like style transfer, semantic image segmentation, and semantic image synthesis, etc. for next week (week 9).

**Comment by shiffman** [comment]
Yes, you can add that stuff to https://github.com/ml5js/Intro-ML-Arts-IMA/blob/source/10_runwayML/README.md! 

I'll also note we fell way behind on training with python last week so Monday will be quite a bit of catchup. I will at least show Runway but realistically we might not get to it until Wednesday next week.

**Comment by ellennickles** [comment]
ok! and really those techniques I mentioned above are generative, so maybe it's okay to focus the basics of inputs and outputs next week and then get into how the neural networks are working in the following week

**Pull request merged**
