### PR TITLE
Pcomp examples

### PR DESCRIPTION
**Pull request by ellennickles**
@shiffman I'm not sure the best way to do this either. Did I just make this more confusing by creating this PR? Since there are no conflicts yet, would it make sense to merge this now so the other reviewers can look at materials for both sessions?

Still thinking about adding a transfer learning example and possibly a multi-pose PoseNet example

### CODE REVIEW

**Review by shiffman — APPROVED** [review]
This is perfect actually! I'm impressed you figured out how to pull request to my branch / pull request! I  agree I will merge this in then everything can be review in one place #34. 

My only concern here is, will all the students have the materials or easy access to the materials? Let's poll the students on Monday and see if anyone did not take Creative Computing (I think they all haave?). Let's discuss!

**Comment by ellennickles** [comment]
> My only concern here is, will all the students have the materials or easy access to the materials?

It used to be that The Shop supplied extra Arduinos for checkout. I'll inquire tomorrow to find out if this is still the case and if they're settled enough after the move to provide these resources.

**Comment by shiffman** [comment]
Also, maybe it makes sense for this assignment to be done in pairs . . or groups of 3?

**Comment by ellennickles** [comment]
That's a great idea! Then I definitely want to include a third example using multi-pose PoseNet. I started one this weekend, but I need to test it with another person before posting.

**Pull request merged**
